# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: CopyFiles@2
  inputs:
    Contents: |
      *\bin\*\*.exe
      *\bin\*\*.dll
    TargetFolder: '$(Build.ArtifactStagingDirectory)/'
    CleanTargetFolder: true
    OverWrite: true


- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'kennethFSDEV'
    repositoryName: 'kennethFSDEV/SteamCMD-Mod-Collection-Manager'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'userSpecifiedTag'
    tag: '1.0.0.2'
    title: 'SteamCMD Mod Collection Manager'
    assets: |
      $(Build.ArtifactStagingDirectory)/*/bin/*/*.exe
      $(Build.ArtifactStagingDirectory)/*/bin/*/*.dll
    isPreRelease: true
    addChangeLog: false

